POST http://localhost:5000/add
Content-Type: application/json

{
    "name": "sai",
    "email":"sai@gmail.com",
    "phone": "9876543219"
}
 
###
GET http://localhost:5000/contact/67f2534222419f59a20e3606

###
GET  http://localhost:5000/

###
PUT http://localhost:5000/update/67f255683c1750505ad1b91b
Content-Type: application/json

{
    "name": "sai",
    "email":"sai@gmail.com",
    "phone": "999"
}
 
###
DELETE http://localhost:5000/delete/67f255683c1750505ad1b91b